AllCops:
  NewCops: enable
  Exclude:
    - 'db/seeds/**/*'
    - 'node_modules/**/*'

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 54

Metrics/BlockLength:
  Max: 33
  Exclude:
    - 'db/schema.rb'
    - 'config/environments/development.rb'

Metrics/MethodLength:
  Max: 30

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'
    - 'config/deploy.rb'

Style/MissingRespondToMissing:
  Enabled: true

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Layout/LineLength:
  Exclude:
    - 'db/seeds.rb'
    - 'config/initializers/devise.rb'
  Max: 190

Style/CommentedKeyword:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
    - 'bin/bundle'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'bin/yarn'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'


Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/ArgumentAlignment:
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

Layout/ExtraSpacing:
  Exclude:
    - 'db/seeds.rb'

Layout/SpaceAfterComma:
  Exclude:
    - 'db/seeds.rb'

Layout/SpaceAroundOperators:
  Exclude:
    - 'db/seeds.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/deploy.rb'

Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/SpecialGlobalVars:
  Exclude:
    - 'bin/bundle'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/bombers_controller.rb'
    - 'app/models/player.rb'

Style/MultilineBlockChain:
  Exclude:
    - 'app/controllers/bombers_controller.rb'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Layout/HashAlignment:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/SwapValues:
  Enabled: true
