default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  timeout:  5000
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['LOCAL'].blank? ? ENV['DB_PASSWORD'] : 111111 %>
  host:     <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] if ENV['LOCAL'].blank? %>
  port:     <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] if ENV['LOCAL'].blank? %>

development:
  <<: *default

production:
  <<: *default
