development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:
      token: <%= ENV["BOT_TOKEN"] %>
      username: <%= ENV["BOT_NAME"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:
      token: <%= ENV["BOT_TOKEN"] %>
      username: <%= ENV["BOT_NAME"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:
      token: <%= ENV["BOT_TOKEN"] %>
      username: <%= ENV["BOT_NAME"] %>