# frozen_string_literal: true

Team.create(code: 'purple', name: 'Фиолетовые', num: 1)
Team.create(code: 'green',  name: 'Зеленые',    num: 2)
Team.create(code: 'white',  name: 'Белые',      num: 3)
Team.create(code: 'color1', name: 'Цветные1',   num: 4)
Team.create(code: 'color2', name: 'Цветные2',   num: 5)

Role.create(code:  'admin',   name: 'Администратор')
Role.create(code:  'captain', name: 'Капитан команды')
Role.create(code:  'player',  name: 'Игрок')

Player.create(code:  1, comment: '',     lastname: 'Солоян',      name: 'Гарик',       middlename: 'Эдуардович',    birthday: '11.07.1989', phone: '9269494205', role_id: 3, password: '269405', email: '9269494205@krsz.ru')
Player.create(code:  2, comment: '',     lastname: 'Новик',       name: 'Николай',     middlename: 'Александрович', birthday: '12.11.1972', phone: nil,          role_id: 2, password: '000000', email: '02@krsz.ru')
Player.create(code:  3, comment: '',     lastname: 'Глобчанский', name: 'Денис',       middlename: '',              birthday: '',           phone: '9999814390', role_id: 3, password: '000000', email: 'globchansky.denis@gmail.com')
Player.create(code:  4, comment: '',     lastname: 'Абулов',      name: 'Шахин',       middlename: '',              birthday: '',           phone: '9774657581', role_id: 2, password: '775781', email: '9774657581@krsz.ru')
Player.create(code:  5, comment: '',     lastname: 'Абдулаев',    name: 'Алихан',      middlename: 'Лечиевич',      birthday: '01.09.1966', phone: '9257720113', role_id: 3, password: '252013', email: '9257720113@krsz.ru')
Player.create(code:  6, comment: '',     lastname: '',            name: 'Тигран',      middlename: '',              birthday: '',           phone: '9859983970', role_id: 3, password: '858370', email: '9859983970@krsz.ru')
Player.create(code:  7, comment: '',     lastname: 'Никурадзе',   name: 'Сандро',      middlename: '',              birthday: '',           phone: '9263947752', role_id: 2, password: '264752', email: '9263947752@krsz.ru')
Player.create(code:  8, comment: '',     lastname: 'Пятницкий',   name: 'Дмитрий',     middlename: 'Владимирович',  birthday: '07.07.1990', phone: '9851857742', role_id: 3, password: '855742', email: '9851857742@krsz.ru')
Player.create(code:  9, comment: '',     lastname: 'Федунов',     name: 'Владимир',    middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '09@krsz.ru')
Player.create(code: 10, comment: '',     lastname: '',            name: 'Виталий',     middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '10@krsz.ru')
Player.create(code: 11, comment: '_лыж', lastname: '',            name: 'Александр',   middlename: '',              birthday: '',           phone: '9154379667', role_id: 3, password: '157967', email: '9154379667@krsz.ru')
Player.create(code: 12, comment: '_вод', lastname: 'Кулявцев',    name: 'Александр',   middlename: '',              birthday: '',           phone: '9036784403', role_id: 3, password: '038403', email: '9036784403@krsz.ru')
Player.create(code: 13, comment: '',     lastname: 'Эйвазов',     name: 'Араз',        middlename: 'Гаджиахмедович',birthday: '13.08.1995', phone: '9162336042', role_id: 1, password: '163642', email: '9162336042@krsz.ru')
Player.create(code: 14, comment: '',     lastname: 'Порожкин',    name: 'Александр',   middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '14@krsz.ru')
Player.create(code: 15, comment: '',     lastname: '',            name: 'Котэ',        middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '15@krsz.ru')
Player.create(code: 16, comment: '',     lastname: 'Салосятов',   name: 'Василий',     middlename: 'Евгеньевич',    birthday: '15.08.1987', phone: nil,          role_id: 3, password: '000000', email: '16@krsz.ru')
Player.create(code: 17, comment: '',     lastname: 'Трубаров',    name: 'Андрей',      middlename: 'Анатольевич',   birthday: '24.07.1987', phone: '9299775687', role_id: 1, password: '297587', email: '9299775687@krsz.ru')
Player.create(code: 18, comment: '',     lastname: 'Морозов',     name: 'Дмитрий',     middlename: 'Михайлович',    birthday: '28.04.1996', phone: '9055561736', role_id: 3, password: '056136', email: '9055561736@krsz.ru')
Player.create(code: 19, comment: '',     lastname: 'Кошелапов',   name: 'Иван',        middlename: '',              birthday: '01.01.1988', phone: '9252233115', role_id: 3, password: '253315', email: '9252233115@krsz.ru')
Player.create(code: 20, comment: '',     lastname: '',            name: 'Михаил',      middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '20@krsz.ru')
Player.create(code: 21, comment: '',     lastname: 'Витвицкий',   name: 'Дмитрий',     middlename: 'Владимирович',  birthday: '26.08.1983', phone: '9191087399', role_id: 1, password: '111111', email: 'dvitvitskiy.pro@gmail.com')
Player.create(code: 22, comment: '',     lastname: '',            name: 'Илья',        middlename: '',              birthday: '',           phone: '9013318640', role_id: 3, password: '011840', email: '9013318640@krsz.ru')
Player.create(code: 23, comment: '_вра', lastname: '',            name: 'Сергей',      middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '23@krsz.ru')
Player.create(code: 24, comment: '',     lastname: '',            name: 'Эльнар',      middlename: '',              birthday: '',           phone: '9687179693', role_id: 3, password: '687993', email: '9687179693@krsz.ru')
Player.create(code: 25, comment: '_отж', lastname: 'Соколовский', name: 'Сергей',      middlename: '',              birthday: '18.05.1983', phone: '9163355533', role_id: 3, password: '165533', email: '9163355533@krsz.ru')
Player.create(code: 26, comment: '',     lastname: 'Новик',       name: 'Глеб',        middlename: 'Николаевич',    birthday: '26.04.2003', phone: nil,          role_id: 3, password: '000000', email: '26@krsz.ru')
Player.create(code: 27, comment: '',     lastname: 'Новик',       name: 'Святослав',   middlename: 'Николаевич',    birthday: '12.05.1995', phone: nil,          role_id: 3, password: '000000', email: '27@krsz.ru')
Player.create(code: 28, comment: '_евр', lastname: '',            name: 'Андрей',      middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '28@krsz.ru')
Player.create(code: 29, comment: '',     lastname: 'Камышик',     name: 'Максим',      middlename: 'Николаевич',    birthday: '08.01.1982', phone: nil,          role_id: 3, password: '000000', email: '29@krsz.ru')
Player.create(code: 30, comment: '_рыж', lastname: '',            name: 'Николай',     middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '30@krsz.ru')
Player.create(code: 31, comment: '',     lastname: '1',           name: 'Михаил',      middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '31@krsz.ru')
Player.create(code: 32, comment: '_сер', lastname: '5',           name: 'noname',      middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '32@krsz.ru')
Player.create(code: 33, comment: '_x6',  lastname: 'Аникеев',     name: 'Максим',      middlename: 'Викторович',    birthday: '05.06.1984', phone: nil,          role_id: 3, password: '000000', email: '33@krsz.ru')
Player.create(code: 34, comment: '',     lastname: 'Миротинцев',  name: 'Егор',        middlename: '',              birthday: '',           phone: '9166945280', role_id: 3, password: '000000', email: '34@krsz.ru')
Player.create(code: 35, comment: '_врат',lastname: '',            name: '',            middlename: '',              birthday: '',           phone: nil,          role_id: 3, password: '000000', email: '35@krsz.ru')
# Player.create(code: 36, comment: '',     lastname: '',  name: '',   middlename: '',      birthday: '',      phone: nil,          role_id: 3, password: '000000', email: '36@krsz.ru')

d1 = Day.create(date: '21.10.2019'.to_date)
d1t1p1 = d1.day_players.create(team_id: 1, player_id: 2)
d1t1p2 = d1.day_players.create(team_id: 1, player_id: 5)
d1t1p3 = d1.day_players.create(team_id: 1, player_id: 6)
d1t1p4 = d1.day_players.create(team_id: 1, player_id: 8)
d1t1p5 = d1.day_players.create(team_id: 1, player_id: 11)
d1t1p6 = d1.day_players.create(team_id: 1, player_id: 18)
d1t1p7 = d1.day_players.create(team_id: 1, player_id: 23)
d1t2p1 = d1.day_players.create(team_id: 2, player_id: 4)
d1t2p2 = d1.day_players.create(team_id: 2, player_id: 10)
d1t2p3 = d1.day_players.create(team_id: 2, player_id: 12)
d1t2p4 = d1.day_players.create(team_id: 2, player_id: 13)
d1t2p5 = d1.day_players.create(team_id: 2, player_id: 12)
d1t2p6 = d1.day_players.create(team_id: 2, player_id: 20)
d1t3p1 = d1.day_players.create(team_id: 3, player_id: 1)
d1t3p2 = d1.day_players.create(team_id: 3, player_id: 7)
d1t3p3 = d1.day_players.create(team_id: 3, player_id: 9)
d1t3p4 = d1.day_players.create(team_id: 3, player_id: 19)
d1t3p5 = d1.day_players.create(team_id: 3, player_id: 21)
d1t3p6 = d1.day_players.create(team_id: 3, player_id: 22)
g1 = Game.create(day_id: d1.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
g2 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 1, goals_right: 0, team_right_id: 2)
g2.goals.create(team_id: g2.team_left_id, player_id: 18)
g3 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 1, goals_right: 1, team_right_id: 3)
g3.goals.create(team_id: 4, player_id: 8)
g3.goals.create(team_id: 3, player_id: 1)
g4 = Game.create(day_id: d1.id, team_left_id: 2, goals_left: 2, goals_right: 1, team_right_id: 3)
g4.goals.create(team_id: 3, player_id: 1)
g4.goals.create(team_id: 2, player_id: 13)
g4.goals.create(team_id: 2, player_id: 13)
g5 = Game.create(day_id: d1.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 4)
g5.goals.create(team_id: 2, player_id: 13)
g6 = Game.create(day_id: d1.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 3)
g6.goals.create(team_id: 2, player_id: 12)
g6.goals.create(team_id: 3, player_id: 21)
g7 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 0, goals_right: 0, team_right_id: 3)
g8 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 0, goals_right: 0, team_right_id: 2)
g8.goals.create(team_id: g8.team_left_id, player_id: 18)
g9 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 3)
g9.goals.create(team_id: 3, player_id: 17)
g9.goals.create(team_id: 3, player_id: 7)
g10 = Game.create(day_id: d1.id, team_left_id: 2, goals_left: 0, goals_right: 0, team_right_id: 3)
g11 = Game.create(day_id: d1.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 4)
g11.goals.create(team_id: 2, player_id: 4)
g11.goals.create(team_id: 4, player_id: 14)
g12 = Game.create(day_id: d1.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 4)
g12.goals.create(team_id: 3, player_id: 1)
g12.goals.create(team_id: 3, player_id: 19)
g13 = Game.create(day_id: d1.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 2)
g13.goals.create(team_id: 3, player_id: 7)
g13.goals.create(team_id: 2, player_id: 20)
g14 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 2, goals_right: 0, team_right_id: 2)
g14.goals.create(team_id: 4, player_id: 3)
g14.goals.create(team_id: 4, player_id: 18)
g15 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 0, goals_right: 1, team_right_id: 3)
g15.goals.create(team_id: 3, player_id: 19)
g16 = Game.create(day_id: d1.id, team_left_id: 2, goals_left: 0, goals_right: 1, team_right_id: 3)
g16.goals.create(team_id: 3, player_id: 22)
g17 = Game.create(day_id: d1.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 4)
g17.goals.create(team_id: 2, player_id: 4)
g18 = Game.create(day_id: d1.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 3)
g18.goals.create(team_id: 2, player_id: 6)
g18.goals.create(team_id: 3, player_id: 21)
g19 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 1, goals_right: 1, team_right_id: 3)
g19.goals.create(team_id: 4, player_id: 18)
g19.goals.create(team_id: 3, player_id: 7)
g20 = Game.create(day_id: d1.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 2)
g20.goals.create(team_id: 2, player_id: 16)
g20.goals.create(team_id: 2, player_id: 6)
g21 = Game.create(day_id: d1.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 2)
g22 = Game.create(day_id: d1.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 4)
g22.goals.create(team_id: 4, player_id: 18)
g22.goals.create(team_id: 3, player_id: 7)
g22.goals.create(team_id: 3, player_id: 19)

d2 = Day.create(date: '28.10.2019'.to_date)
d2t3p1 = d2.day_players.create(team_id: 3, player_id: 21)
d2t3p2 = d2.day_players.create(team_id: 3, player_id: 17)
d2t3p3 = d2.day_players.create(team_id: 3, player_id: 22)
d2t3p4 = d2.day_players.create(team_id: 3, player_id: 19)
d2t3p5 = d2.day_players.create(team_id: 3, player_id: 7)
d2t3p6 = d2.day_players.create(team_id: 3, player_id: 1)
d2t2p1 = d2.day_players.create(team_id: 2, player_id: 13)
d2t2p2 = d2.day_players.create(team_id: 2, player_id: 10)
d2t2p3 = d2.day_players.create(team_id: 2, player_id: 8)
d2t2p4 = d2.day_players.create(team_id: 2, player_id: 30)
d2t2p5 = d2.day_players.create(team_id: 2, player_id: 12)
d2t2p6 = d2.day_players.create(team_id: 2, player_id: 3)
d2t4p1 = d2.day_players.create(team_id: 4, player_id: 14)
d2t4p2 = d2.day_players.create(team_id: 4, player_id: 18)
d2t4p3 = d2.day_players.create(team_id: 4, player_id: 6)
d2t4p4 = d2.day_players.create(team_id: 4, player_id: 23)
d2t4p5 = d2.day_players.create(team_id: 4, player_id: 16)
d2t5p1 = d2.day_players.create(team_id: 5, player_id: 35)
d2t5p2 = d2.day_players.create(team_id: 5, player_id: 20)
d2t5p3 = d2.day_players.create(team_id: 5, player_id: 32)
h1 = Game.create(day_id: d2.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 4)
h1.goals.create(team_id: 3, player_id: 7)
h1.goals.create(team_id: 3, player_id: 22)
h1.goals.create(team_id: 4, player_id: nil)
h2  = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 1, team_right_id: 2)
h2.goals.create(team_id: 2, player_id: 30)
h3  = Game.create(day_id: d2.id, team_left_id: 4, goals_left: 1, goals_right: 1, team_right_id: 2)
h3.goals.create(team_id: 4, player_id: 6)
h3.goals.create(team_id: 2, player_id: 8)
h4  = Game.create(day_id: d2.id, team_left_id: 4, goals_left: 0, goals_right: 0, team_right_id: 5)
h5  = Game.create(day_id: d2.id, team_left_id: 4, goals_left: 1, goals_right: 1, team_right_id: 3)
h5.goals.create(team_id: 4, player_id: 6)
h5.goals.create(team_id: 3, player_id: 1)
h6  = Game.create(day_id: d2.id, team_left_id: 5, goals_left: 0, goals_right: 1, team_right_id: 2)
h6.goals.create(team_id: 2, player_id: 8)
h7  = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 0, team_right_id: 2)
h8  = Game.create(day_id: d2.id, team_left_id: 5, goals_left: 0, goals_right: 2, team_right_id: 4)
h8.goals.create(team_id: 4, player_id: 6)
h8.goals.create(team_id: 4, player_id: 6)
h9  = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 1, goals_right: 1, team_right_id: 4)
h9.goals.create(team_id: 3, player_id: 7)
h9.goals.create(team_id: 4, player_id: 31)
h10 = Game.create(day_id: d2.id, team_left_id: 5, goals_left: 0, goals_right: 2, team_right_id: 2)
h10.goals.create(team_id: 2, player_id: 8)
h10.goals.create(team_id: 2, player_id: 8)
h11 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 2, goals_right: 0, team_right_id: 2)
h11.goals.create(team_id: 3, player_id: 19)
h11.goals.create(team_id: 3, player_id: 21)
h12 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 1, goals_right: 0, team_right_id: 4)
h12.goals.create(team_id: 3, player_id: 19)
h13 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 1, goals_right: 0, team_right_id: 5)
h13.goals.create(team_id: 3, player_id: 1)
h14 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 0, team_right_id: 2)
h15 = Game.create(day_id: d2.id, team_left_id: 5, goals_left: 0, goals_right: 1, team_right_id: 4)
h15.goals.create(team_id: 4, player_id: 14)
h16 = Game.create(day_id: d2.id, team_left_id: 2,  goals_left: 0, goals_right: 1, team_right_id: 4)
h16.goals.create(team_id: 4, player_id: 18)
h17 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 1, goals_right: 0, team_right_id: 4)
h17.goals.create(team_id: 3, player_id: 21)
h18 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 1, team_right_id: 5)
h18.goals.create(team_id: 5, player_id: 32)
h19 = Game.create(day_id: d2.id, team_left_id: 2,  goals_left: 1, goals_right: 1, team_right_id: 5)
h19.goals.create(team_id: 2, player_id: 8)
h19.goals.create(team_id: 5, player_id: 32)
h20 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 1, team_right_id: 4)
h20.goals.create(team_id: 4, player_id: 23)
h21 = Game.create(day_id: d2.id, team_left_id: 2,  goals_left: 1, goals_right: 0, team_right_id: 4)
h21.goals.create(team_id: 2, player_id: 30)
h22 = Game.create(day_id: d2.id, team_left_id: 2,  goals_left: 0, goals_right: 0, team_right_id: 5)

d3 = Day.create(date: '06.11.2019'.to_date)
d3t1p1 = d3.day_players.create(team_id: 1, player_id: 1)
d3t1p2 = d3.day_players.create(team_id: 1, player_id: 33)
d3t1p3 = d3.day_players.create(team_id: 1, player_id: 16)
d3t1p4 = d3.day_players.create(team_id: 1, player_id: 6)
d3t1p5 = d3.day_players.create(team_id: 1, player_id: 23)
d3t1p6 = d3.day_players.create(team_id: 1, player_id: 32)
d3t2p1 = d3.day_players.create(team_id: 2, player_id: 4)
d3t2p2 = d3.day_players.create(team_id: 2, player_id: 10)
d3t2p3 = d3.day_players.create(team_id: 2, player_id: 12)
d3t2p4 = d3.day_players.create(team_id: 2, player_id: 13)
d3t2p5 = d3.day_players.create(team_id: 2, player_id: 3)
d3t3p1 = d3.day_players.create(team_id: 3, player_id: 21)
d3t3p2 = d3.day_players.create(team_id: 3, player_id: 17)
d3t3p3 = d3.day_players.create(team_id: 3, player_id: 7)
d3t3p4 = d3.day_players.create(team_id: 3, player_id: 19)
d3t3p5 = d3.day_players.create(team_id: 3, player_id: 34)
i1  = Game.create(day_id: d3.id, team_left_id: 2, goals_left: 0, goals_right: 0, team_right_id: 1)
i2  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 2)
i2.goals.create(team_id: 3, player_id: 21)
i2.goals.create(team_id: 3, player_id: 17)
i3  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 1)
i3.goals.create(team_id: 3, player_id: 19)
i3.goals.create(team_id: 3, player_id: 7)
i3.goals.create(team_id: 1, player_id: 33)
i4  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 2)
i5  = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 2)
i5.goals.create(team_id: 1, player_id: 16)
i5.goals.create(team_id: 2, player_id: 4)
i5.goals.create(team_id: 2, player_id: 12)
i6  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 2)
i6.goals.create(team_id: 3, player_id: 21)
i6.goals.create(team_id: 3, player_id: 17)
i6.goals.create(team_id: 2, player_id: 4)
i7  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 1)
i8  = Game.create(day_id: d3.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
i8.goals.create(team_id: 1, player_id: 1)
i8.goals.create(team_id: 1, player_id: 14)
i9  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 1)
i9.goals.create(team_id: 3, player_id: 19)
i10 = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 2)
i11 = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 2)
i11.goals.create(team_id: 2, player_id: 4)
i11.goals.create(team_id: 2, player_id: 13)
i12 = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 1, goals_right: 2, team_right_id: 2)
i12.goals.create(team_id: 3, player_id: 19)
i12.goals.create(team_id: 2, player_id: 4)
i12.goals.create(team_id: 2, player_id: 3)
i13 = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
i13.goals.create(team_id: 1, player_id: 1)
i13.goals.create(team_id: 1, player_id: 1)
i14 = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 3)
i14.goals.create(team_id: 1, player_id: 23)
i14.goals.create(team_id: 3, player_id: 19)
i15 = Game.create(day_id: d3.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 3)
i15.goals.create(team_id: 2, player_id: 3)
i16 = Game.create(day_id: d3.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 1)
i16.goals.create(team_id: 2, player_id: 13)
i16.goals.create(team_id: 1, player_id: 32)
i17 = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
i17.goals.create(team_id: 3, player_id: 7)
i17.goals.create(team_id: 3, player_id: 34)
i18 = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
i18.goals.create(team_id: 2, player_id: 4)
i19 = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 2)
i19.goals.create(team_id: 1, player_id: 6)
i19.goals.create(team_id: 2, player_id: 12)

d4  = Day.create(date: '11.11.2019'.to_date)
d4t1p1 = d4.day_players.create(team_id: 1, player_id: 2)
d4t1p2 = d4.day_players.create(team_id: 1, player_id: 6)
d4t1p3 = d4.day_players.create(team_id: 1, player_id: 5)
d4t1p4 = d4.day_players.create(team_id: 1, player_id: 25)
d4t1p5 = d4.day_players.create(team_id: 1, player_id: 23)
d4t1p6 = d4.day_players.create(team_id: 1, player_id: 14)
d4t1p7 = d4.day_players.create(team_id: 1, player_id: 31)
d4t2p1 = d4.day_players.create(team_id: 2, player_id: 4)
d4t2p2 = d4.day_players.create(team_id: 2, player_id: 13)
d4t2p3 = d4.day_players.create(team_id: 2, player_id: 10)
d4t2p4 = d4.day_players.create(team_id: 2, player_id: 8)
d4t2p5 = d4.day_players.create(team_id: 2, player_id: 12)
d4t2p6 = d4.day_players.create(team_id: 2, player_id: 16)
d4t2p7 = d4.day_players.create(team_id: 2, player_id: 30)
d4t3p1 = d4.day_players.create(team_id: 3, player_id: 21)
d4t3p2 = d4.day_players.create(team_id: 3, player_id: 19)
d4t3p3 = d4.day_players.create(team_id: 3, player_id: 22)
d4t3p4 = d4.day_players.create(team_id: 3, player_id: 1)
d4t3p5 = d4.day_players.create(team_id: 3, player_id: 7)
d4t3p6 = d4.day_players.create(team_id: 3, player_id: 28)
d4t3p7 = d4.day_players.create(team_id: 3, player_id: 34)
j1  = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 1)
j1.goals.create(team_id: 3, player_id: nil)
j2  = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
j2.goals.create(team_id: 2, player_id: 13)
j3  = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 2)
j3.goals.create(team_id: 2, player_id: 13)
j3.goals.create(team_id: 1, player_id: 23)
j3.goals.create(team_id: 1, player_id: 25)
j4  = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 3)
j4.goals.create(team_id: 3, player_id: 1)
j4.goals.create(team_id: 3, player_id: 19)
j5  = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 3)
j5.goals.create(team_id: 2, player_id: 4)
j6  = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
j6.goals.create(team_id: 1, player_id: 25)
j6.goals.create(team_id: 1, player_id: 31)
j7  = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 1)
j7.goals.create(team_id: 1, player_id: nil)
j8  = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 2, goals_right: 0, team_right_id: 1)
j8.goals.create(team_id: 2, player_id: 8)
j8.goals.create(team_id: 2, player_id: 10)
j9  = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 3)
j9.goals.create(team_id: 1, player_id: 25)
j9.goals.create(team_id: 3, player_id: 21)
j9.goals.create(team_id: 3, player_id: 19)
j10 = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 3)
j10.goals.create(team_id: 2, player_id: 4)
j10.goals.create(team_id: 3, player_id: 7)
j11 = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 2, goals_right: 0, team_right_id: 1)
j11.goals.create(team_id: 2, player_id: 13)
j11.goals.create(team_id: 2, player_id: 8)
j12 = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 1, goals_right: 2, team_right_id: 3)
j12.goals.create(team_id: 2, player_id: 8)
j12.goals.create(team_id: 3, player_id: 7)
j12.goals.create(team_id: 3, player_id: 34)
j13 = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 3)
j13.goals.create(team_id: 1, player_id: 25)
j13.goals.create(team_id: 3, player_id: 7)
j14 = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 2)
j14.goals.create(team_id: 2, player_id: 8)
j14.goals.create(team_id: 2, player_id: 4)
j15 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 1, goals_right: 2, team_right_id: 2)
j15.goals.create(team_id: 3, player_id: 1)
j15.goals.create(team_id: 2, player_id: 8)
j15.goals.create(team_id: 2, player_id: 4)
j16 = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 0, goals_right: 1, team_right_id: 2)
j16.goals.create(team_id: 2, player_id: 8)
j17 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 2)
j17.goals.create(team_id: 2, player_id: 13)
j17.goals.create(team_id: 3, player_id: 21)
j18 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
j18.goals.create(team_id: 3, player_id: 1)
j18.goals.create(team_id: 3, player_id: 1)
j19 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 2)
j19.goals.create(team_id: 3, player_id: 1)
j19.goals.create(team_id: 3, player_id: 7)
j19.goals.create(team_id: 2, player_id: 8)
j20 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
j20.goals.create(team_id: 3, player_id: 1)
j20.goals.create(team_id: 3, player_id: 34)
j21 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 2)
j21.goals.create(team_id: 3, player_id: 1)
j21.goals.create(team_id: 2, player_id: 4)
i19.goals.create(team_id: 2, player_id: 13)

d5  = Day.create(date: '13.11.2019'.to_date)
d5t1p1 = d5.day_players.create(team_id: 1, player_id: 2)  # Коля Н
d5t1p2 = d5.day_players.create(team_id: 1, player_id: 33) # Макс А
d5t1p3 = d5.day_players.create(team_id: 1, player_id: 29) # Макс К
d5t1p4 = d5.day_players.create(team_id: 1, player_id: 18) # Дима М
d5t1p5 = d5.day_players.create(team_id: 1, player_id: 5)  # Алихан
d5t2p1 = d5.day_players.create(team_id: 2, player_id: 4)  # Шах
d5t2p2 = d5.day_players.create(team_id: 2, player_id: 13) # Араз
d5t2p3 = d5.day_players.create(team_id: 2, player_id: 10) # Виталик
d5t2p4 = d5.day_players.create(team_id: 2, player_id: 25) # Серега С
d5t2p5 = d5.day_players.create(team_id: 2, player_id: 6)  # Тигран
d5t3p1 = d5.day_players.create(team_id: 3, player_id: 21) # Я
d5t3p2 = d5.day_players.create(team_id: 3, player_id: 22) # Илья
d5t3p3 = d5.day_players.create(team_id: 3, player_id: 17) # Андр
d5t3p4 = d5.day_players.create(team_id: 3, player_id: 19) # Ваня
d5t3p5 = d5.day_players.create(team_id: 3, player_id: 7)  # Сандро
d5t3p6 = d5.day_players.create(team_id: 3, player_id: 1)  # Гарик
d5t4p1 = d5.day_players.create(team_id: 4, player_id: 1)  # Гарик
d5t4p2 = d5.day_players.create(team_id: 4, player_id: 34) # Егор
d5t4p3 = d5.day_players.create(team_id: 4, player_id: 3)  # Ден
d5t4p4 = d5.day_players.create(team_id: 4, player_id: 14) # Саша П
d5t4p5 = d5.day_players.create(team_id: 4, player_id: 16) # Вася
d5t4p6 = d5.day_players.create(team_id: 4, player_id: 31) # Миша
h1  = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 3)
h1.goals.create(team_id: 3, player_id: 19)
h1.goals.create(team_id: 3, player_id: 21)
h2  = Game.create(day_id: d5.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 3)
h2.goals.create(team_id: 1, player_id: 29)
h2.goals.create(team_id: 3, player_id: 7)
h2.goals.create(team_id: 3, player_id: 22)
h3  = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 2, goals_right: 0, team_right_id: 3)
h3.goals.create(team_id: 2, player_id: 25)
h3.goals.create(team_id: 2, player_id: 25)
h4  = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 2, goals_right: 1, team_right_id: 1)
h4.goals.create(team_id: 2, player_id: 25)
h4.goals.create(team_id: 2, player_id: 13)
h4.goals.create(team_id: 1, player_id: 29)
h5  = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 3)
h5.goals.create(team_id: 2, player_id: 4)
h6  = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 0, goals_right: 0, team_right_id: 1)
h7  = Game.create(day_id: d5.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 1)
h7.goals.create(team_id: 1, player_id: 2)
h7.goals.create(team_id: 1, player_id: 18)
h8  = Game.create(day_id: d5.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
h8.goals.create(team_id: 1, player_id: 2)
h8.goals.create(team_id: 1, player_id: 29)
h9  = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
h9.goals.create(team_id: 1, player_id: 2)
h9.goals.create(team_id: 1, player_id: 18)
h10 = Game.create(day_id: d5.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 1)
h10.goals.create(team_id: 1, player_id: 2)
h10.goals.create(team_id: 1, player_id: 18)
h11 = Game.create(day_id: d5.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 1)
h12 = Game.create(day_id: d5.id, team_left_id: 4, goals_left: 0, goals_right: 1, team_right_id: 2)
h12.goals.create(team_id: 2, player_id: 13)
h13 = Game.create(day_id: d5.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 2)
h13.goals.create(team_id: 3, player_id: 1)
h13.goals.create(team_id: 3, player_id: 1)
h13.goals.create(team_id: 2, player_id: 25)
h14 = Game.create(day_id: d5.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 1)
h14.goals.create(team_id: 3, player_id: 1)
h15 = Game.create(day_id: d5.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 4)
h15.goals.create(team_id: 4, player_id: 34)
h15.goals.create(team_id: 4, player_id: 14)
h16 = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 4)
h16.goals.create(team_id: 2, player_id: 25)
h16.goals.create(team_id: 4, player_id: 16)
h17 = Game.create(day_id: d5.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
h17.goals.create(team_id: 1, player_id: 2)
h17.goals.create(team_id: 1, player_id: 18)
h18 = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 0, goals_right: 1, team_right_id: 1)
h18.goals.create(team_id: 1, player_id: 18)
h19 = Game.create(day_id: d5.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 1)
h19.goals.create(team_id: 1, player_id: 2)
h19.goals.create(team_id: 1, player_id: 29)
h20 = Game.create(day_id: d5.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
h20.goals.create(team_id: 1, player_id: 18)
h20.goals.create(team_id: 1, player_id: 33)
h21 = Game.create(day_id: d5.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 1)
h21.goals.create(team_id: 1, player_id: 2)
h21.goals.create(team_id: 1, player_id: 18)
h22 = Game.create(day_id: d5.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 1)
h23 = Game.create(day_id: d5.id, team_left_id: 2, goals_left: 0, goals_right: 1, team_right_id: 4)
h23.goals.create(team_id: 4, player_id: 14)

d6  = Day.create(date: '18.11.2019'.to_date)
d6t1p1 = d6.day_players.create(team_id: 1, player_id: 2)  # Коля Н
d6t1p2 = d6.day_players.create(team_id: 1, player_id: 25) # Серега С
d6t1p3 = d6.day_players.create(team_id: 1, player_id: 6)  # Тигран
d6t1p4 = d6.day_players.create(team_id: 1, player_id: 18) # Дима М
d6t1p5 = d6.day_players.create(team_id: 1, player_id: 5)  # Алихан
d6t1p6 = d6.day_players.create(team_id: 1, player_id: 23) # Серега врач

d6t2p1 = d6.day_players.create(team_id: 2, player_id: 4)  # Шах
d6t2p2 = d6.day_players.create(team_id: 2, player_id: 13) # Араз
d6t2p3 = d6.day_players.create(team_id: 2, player_id: 10) # Виталик
d6t2p4 = d6.day_players.create(team_id: 2, player_id: 30) # Коля Рыж
d6t2p5 = d6.day_players.create(team_id: 2, player_id: 12) # Саня Вод
d6t2p6 = d6.day_players.create(team_id: 2, player_id: 35) # Вратарь

d6t3p1 = d6.day_players.create(team_id: 3, player_id: 21) # Я
d6t3p2 = d6.day_players.create(team_id: 3, player_id: 22) # Илья
d6t3p3 = d6.day_players.create(team_id: 3, player_id: 17) # Андр
d6t3p4 = d6.day_players.create(team_id: 3, player_id: 19) # Ваня
d6t3p5 = d6.day_players.create(team_id: 3, player_id: 7)  # Сандро
d6t3p6 = d6.day_players.create(team_id: 3, player_id: 1)  # Гарик

d6t4p1 = d6.day_players.create(team_id: 4, player_id: 9)  # Вова
d6t4p2 = d6.day_players.create(team_id: 4, player_id: 34) # Егор
d6t4p3 = d6.day_players.create(team_id: 4, player_id: 3)  # Ден
d6t4p4 = d6.day_players.create(team_id: 4, player_id: 14) # Саша П
d6t4p5 = d6.day_players.create(team_id: 4, player_id: 16) # Вася
d6t4p6 = d6.day_players.create(team_id: 4, player_id: 20) # Миша Белый
d6t4p6 = d6.day_players.create(team_id: 4, player_id: 8)  # Дима П
h1  = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 2)
h2  = Game.create(day_id: d6.id, team_left_id: 4, goals_left: 0, goals_right: 1, team_right_id: 1)
h2.goals.create(team_id: 1, player_id: 2)
h3  = Game.create(day_id: d6.id, team_left_id: 2, goals_left: 1, goals_right: 2, team_right_id: 1)
h3.goals.create(team_id: 2, player_id: 12)
h3.goals.create(team_id: 1, player_id: 25)
h3.goals.create(team_id: 1, player_id: 18)
h4  = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
h4.goals.create(team_id: 1, player_id: 25)
h4.goals.create(team_id: 1, player_id: 2)
h5  = Game.create(day_id: d6.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 1)
h5.goals.create(team_id: 1, player_id: 25)
h5.goals.create(team_id: 1, player_id: 25)
h6  = Game.create(day_id: d6.id, team_left_id: 2, goals_left: 2, goals_right: 1, team_right_id: 1)
h6.goals.create(team_id: 2, player_id: 12)
h6.goals.create(team_id: 2, player_id: 10)
h6.goals.create(team_id: 1, player_id: 25)
h7  = Game.create(day_id: d6.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 3)
h7.goals.create(team_id: 2, player_id: 4)
h8  = Game.create(day_id: d6.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 4)
h8.goals.create(team_id: 2, player_id: 4)
h9  = Game.create(day_id: d6.id, team_left_id: 2, goals_left: 0, goals_right: 0, team_right_id: 1)
h10 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 4)
h10.goals.create(team_id: 3, player_id: 21)
h10.goals.create(team_id: 4, player_id: 3)
h11 = Game.create(day_id: d6.id, team_left_id: 2, goals_left: 0, goals_right: 1, team_right_id: 1)
h11.goals.create(team_id: 1, player_id: 6)
h12 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
h12.goals.create(team_id: 1, player_id: 2)
h12.goals.create(team_id: 1, player_id: nil)
h13 = Game.create(day_id: d6.id, team_left_id: 4, goals_left: 0, goals_right: 1, team_right_id: 1)
h13.goals.create(team_id: 1, player_id: 6)
h14 = Game.create(day_id: d6.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
h14.goals.create(team_id: 1, player_id: 2)
h14.goals.create(team_id: 1, player_id: 18)
h15 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
h15.goals.create(team_id: 3, player_id: 1)
h15.goals.create(team_id: 3, player_id: 1)
h16 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 4)
h17 = Game.create(day_id: d6.id, team_left_id: 2, goals_left: 0, goals_right: 1, team_right_id: 1)
h17.goals.create(team_id: 1, player_id: 25)
h18 = Game.create(day_id: d6.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 1)
h18.goals.create(team_id: 1, player_id: 25)
h18.goals.create(team_id: 1, player_id: 25)
h19 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 1)
h19.goals.create(team_id: 3, player_id: 19)
h20 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 2)
h20.goals.create(team_id: 3, player_id: 7)
h20.goals.create(team_id: 3, player_id: 22)
h20.goals.create(team_id: 2, player_id: 12)
h21 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 4)
h21.goals.create(team_id: 3, player_id: 19)
h22 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 1)
h22.goals.create(team_id: 3, player_id: 1)
h22.goals.create(team_id: 3, player_id: 7)
h22.goals.create(team_id: 1, player_id: 18)
h23 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 2)
h23.goals.create(team_id: 2, player_id: 30)
h23.goals.create(team_id: 2, player_id: 10)
h24 = Game.create(day_id: d6.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 2)
h24.goals.create(team_id: 2, player_id: 4)
h24.goals.create(team_id: 2, player_id: 12)
h25 = Game.create(day_id: d6.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 2)
h25.goals.create(team_id: 3, player_id: 7)
h25.goals.create(team_id: 3, player_id: 21)
