# frozen_string_literal: true

Team.create(code: 'purple', name: 'Фиолетовые', num: 1)
Team.create(code: 'green',  name: 'Зеленые',    num: 2)
Team.create(code: 'white',  name: 'Белые',      num: 3)
Team.create(code: 'color1', name: 'Цветные1',   num: 4)
Team.create(code: 'color2', name: 'Цветные2',   num: 5)
Team.create(code: 'all',    name: 'Все',        num: 0)

Role.create(code:  'admin',   name: 'Администратор')
Role.create(code:  'captain', name: 'Капитан команды')
Role.create(code:  'player',  name: 'Игрок')

Player.create(comment: '',     lastname: 'Солоян',      name: 'Гарик',       middlename: 'Эдуардович',    birthday: '11.07.1989', phone: '9269494205', team_id: 3, code:  1, role_id: 3, password: '269405', email: '9269494205@krsz.ru')
Player.create(comment: '',     lastname: 'Новик',       name: 'Николай',     middlename: 'Александрович', birthday: '12.11.1972', phone: nil,          team_id: 1, code:  2, role_id: 2, password: '000000', email: '02@krsz.ru')
Player.create(comment: '',     lastname: '',            name: 'Денис',       middlename: '',              birthday: '',           phone: nil,          team_id: 4, code:  3, role_id: 3, password: '000000', email: '03@krsz.ru')
Player.create(comment: '',     lastname: 'Абулов',      name: 'Шахин',       middlename: '',              birthday: '',           phone: '9774657581', team_id: 2, code:  4, role_id: 2, password: '775781', email: '9774657581@krsz.ru')
Player.create(comment: '',     lastname: 'Абдулаев',    name: 'Алихан',      middlename: 'Лечиевич',      birthday: '01.09.1966', phone: '9257720113', team_id: 1, code:  5, role_id: 3, password: '252013', email: '9257720113@krsz.ru')
Player.create(comment: '',     lastname: '',            name: 'Тигран',      middlename: '',              birthday: '',           phone: '9859983970', team_id: 1, code:  6, role_id: 3, password: '858370', email: '9859983970@krsz.ru')
Player.create(comment: '',     lastname: 'Никурадзе',   name: 'Сандро',      middlename: '',              birthday: '',           phone: '9263947752', team_id: 3, code:  7, role_id: 2, password: '264752', email: '9263947752@krsz.ru')
Player.create(comment: '',     lastname: 'Пятницкий',   name: 'Дмитрий',     middlename: 'Владимирович',  birthday: '07.07.1990', phone: '9851857742', team_id: 1, code:  8, role_id: 3, password: '855742', email: '9851857742@krsz.ru')
Player.create(comment: '',     lastname: 'Федунов',     name: 'Владимир',    middlename: '',              birthday: '',           phone: nil,          team_id: 3, code:  9, role_id: 3, password: '000000', email: '09@krsz.ru')
Player.create(comment: '',     lastname: '',            name: 'Виталий',     middlename: '',              birthday: '',           phone: nil,          team_id: 2, code: 10, role_id: 3, password: '000000', email: '10@krsz.ru')
Player.create(comment: '_лыж', lastname: '',            name: 'Александр',   middlename: '',              birthday: '',           phone: '9154379667', team_id: 1, code: 11, role_id: 3, password: '157967', email: '9154379667@krsz.ru')
Player.create(comment: '_вод', lastname: 'Кулявцев',    name: 'Александр',   middlename: '',              birthday: '',           phone: '9036784403', team_id: 2, code: 12, role_id: 3, password: '038403', email: '9036784403@krsz.ru')
Player.create(comment: '',     lastname: 'Эйвазов',     name: 'Араз',        middlename: 'Гаджиахмедович',birthday: '13.08.1995', phone: '9162336042', team_id: 2, code: 13, role_id: 1, password: '163642', email: '9162336042@krsz.ru')
Player.create(comment: '',     lastname: 'Порожкин',    name: 'Александр',   middlename: '',              birthday: '',           phone: nil,          team_id: 4, code: 14, role_id: 3, password: '000000', email: '14@krsz.ru')
Player.create(comment: '',     lastname: '',            name: 'Александр',   middlename: '',              birthday: '',           phone: nil,          team_id: 2, code: 15, role_id: 3, password: '000000', email: '15@krsz.ru')
Player.create(comment: '',     lastname: '',            name: 'Василий',     middlename: '',              birthday: '',           phone: nil,          team_id: 4, code: 16, role_id: 3, password: '000000', email: '16@krsz.ru')
Player.create(comment: '',     lastname: 'Трубаров',    name: 'Андрей',      middlename: 'Анатольевич',   birthday: '24.07.1987', phone: '9299775687', team_id: 3, code: 17, role_id: 1, password: '297587', email: '9299775687@krsz.ru')
Player.create(comment: '',     lastname: 'Морозов',     name: 'Дмитрий',     middlename: 'Михайлович',    birthday: '28.04.1996', phone: '9055561736', team_id: 1, code: 18, role_id: 3, password: '056136', email: '9055561736@krsz.ru')
Player.create(comment: '',     lastname: 'Кошелапов',   name: 'Иван',        middlename: '',              birthday: '01.01.1988', phone: '9252233115', team_id: 3, code: 19, role_id: 3, password: '253315', email: '9252233115@krsz.ru')
Player.create(comment: '',     lastname: '',            name: 'Михаил',      middlename: '',              birthday: '',           phone: nil,          team_id: 2, code: 20, role_id: 3, password: '000000', email: '20@krsz.ru')
Player.create(comment: '',     lastname: 'Витвицкий',   name: 'Дмитрий',     middlename: 'Владимирович',  birthday: '26.08.1983', phone: '9191087399', team_id: 3, code: 21, role_id: 1, password: '111111', email: 'dvitvitskiy.pro@gmail.com')
Player.create(comment: '',     lastname: '',            name: 'Илья',        middlename: '',              birthday: '',           phone: '9013318640', team_id: 3, code: 22, role_id: 3, password: '011840', email: '9013318640@krsz.ru')
Player.create(comment: '_вра', lastname: '',            name: 'Сергей',      middlename: '',              birthday: '',           phone: nil,          team_id: 1, code: 23, role_id: 3, password: '000000', email: '23@krsz.ru')
Player.create(comment: '',     lastname: '',            name: 'Эльнар',      middlename: '',              birthday: '',           phone: '9687179693', team_id: 2, code: 24, role_id: 3, password: '687993', email: '9687179693@krsz.ru')
Player.create(comment: '_отж', lastname: '',            name: 'Сергей',      middlename: '',              birthday: '',           phone: '9163355533', team_id: 1, code: 25, role_id: 3, password: '165533', email: '9163355533@krsz.ru')
Player.create(comment: '',     lastname: 'Новик',       name: 'Глеб',        middlename: 'Николаевич',    birthday: '26.04.2003', phone: nil,          team_id: 1, code: 26, role_id: 3, password: '000000', email: '26@krsz.ru')
Player.create(comment: '',     lastname: 'Новик',       name: 'Святослав',   middlename: 'Николаевич',    birthday: '12.05.1995', phone: nil,          team_id: 1, code: 27, role_id: 3, password: '000000', email: '27@krsz.ru')
Player.create(comment: '_евр', lastname: '',            name: 'Андрей',      middlename: '',              birthday: '',           phone: nil,          team_id: 4, code: 28, role_id: 3, password: '000000', email: '28@krsz.ru')
Player.create(comment: '',     lastname: 'Камышик',     name: 'Максим',      middlename: 'Николаевич',    birthday: '08.01.1982', phone: nil,          team_id: 1, code: 29, role_id: 3, password: '000000', email: '29@krsz.ru')
Player.create(comment: '_рыж', lastname: '',            name: 'Николай',     middlename: '',              birthday: '',           phone: nil,          team_id: 2, code: 30, role_id: 3, password: '000000', email: '30@krsz.ru')
Player.create(comment: '',     lastname: '1',           name: 'noname',      middlename: '',              birthday: '',           phone: nil,          team_id: 4, code: 31, role_id: 3, password: '000000', email: '31@krsz.ru')
Player.create(comment: '',     lastname: '5',           name: 'noname',      middlename: '',              birthday: '',           phone: nil,          team_id: 5, code: 32, role_id: 3, password: '000000', email: '32@krsz.ru')
# Player.create(comment: '',     lastname: '',  name: '',   middlename: '',      birthday: '',      phone: nil,          team_id: -, code: -, role_id: 3, password: '000000', email: '-@krsz.ru')

def team(code)
  Team[code].id
end

d1 = '21.10.2019'.to_date
g1 = Game.create(date: d1, team_left_id: team(:white), goals_left: 0, goals_right: 1, team_right_id: team(:green))
g2 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 1, goals_right: 0, team_right_id: team(:green))
g2.goals.create(team_id: g2.team_left_id, player_id: 18)
g3 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 1, goals_right: 1, team_right_id: team(:white))
g3.goals.create(team_id: 4, player_id: 8)
g3.goals.create(team_id: 3, player_id: 1)
g4 = Game.create(date: d1, team_left_id: team(:green), goals_left: 2, goals_right: 1, team_right_id: team(:white))
g4.goals.create(team_id: 3, player_id: 1)
g4.goals.create(team_id: 2, player_id: 13)
g4.goals.create(team_id: 2, player_id: 13)
g5 = Game.create(date: d1, team_left_id: team(:green), goals_left: 1, goals_right: 0, team_right_id: team(:color1))
g5.goals.create(team_id: 2, player_id: 13)
g6 = Game.create(date: d1, team_left_id: team(:green), goals_left: 1, goals_right: 1, team_right_id: team(:white))
g6.goals.create(team_id: 2, player_id: 15)
g6.goals.create(team_id: 3, player_id: 21)
g7 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 0, goals_right: 0, team_right_id: team(:white))
g8 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 0, goals_right: 0, team_right_id: team(:green))
g8.goals.create(team_id: g8.team_left_id, player_id: 18)
g9 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 0, goals_right: 2, team_right_id: team(:white))
g9.goals.create(team_id: 3, player_id: 17)
g9.goals.create(team_id: 3, player_id: 7)
g10 = Game.create(date: d1, team_left_id: team(:green), goals_left: 0, goals_right: 0, team_right_id: team(:white))
g11 = Game.create(date: d1, team_left_id: team(:green), goals_left: 1, goals_right: 1, team_right_id: team(:color1))
g11.goals.create(team_id: 2, player_id: 4)
g11.goals.create(team_id: 4, player_id: 14)
g12 = Game.create(date: d1, team_left_id: team(:white), goals_left: 2, goals_right: 0, team_right_id: team(:color1))
g12.goals.create(team_id: 3, player_id: 1)
g12.goals.create(team_id: 3, player_id: 19)
g13 = Game.create(date: d1, team_left_id: team(:white), goals_left: 1, goals_right: 1, team_right_id: team(:green))
g13.goals.create(team_id: 3, player_id: 7)
g13.goals.create(team_id: 2, player_id: 20)
g14 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 2, goals_right: 0, team_right_id: team(:green))
g14.goals.create(team_id: 4, player_id: 3)
g14.goals.create(team_id: 4, player_id: 18)
g15 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 0, goals_right: 1, team_right_id: team(:white))
g15.goals.create(team_id: 3, player_id: 19)
g16 = Game.create(date: d1, team_left_id: team(:green), goals_left: 0, goals_right: 1, team_right_id: team(:white))
g16.goals.create(team_id: 3, player_id: 22)
g17 = Game.create(date: d1, team_left_id: team(:green), goals_left: 1, goals_right: 0, team_right_id: team(:color1))
g17.goals.create(team_id: 2, player_id: 4)
g18 = Game.create(date: d1, team_left_id: team(:green), goals_left: 1, goals_right: 1, team_right_id: team(:white))
g18.goals.create(team_id: 2, player_id: 6)
g18.goals.create(team_id: 3, player_id: 21)
g19 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 1, goals_right: 1, team_right_id: team(:white))
g19.goals.create(team_id: 4, player_id: 18)
g19.goals.create(team_id: 3, player_id: 7)
g20 = Game.create(date: d1, team_left_id: team(:color1), goals_left: 0, goals_right: 2, team_right_id: team(:green))
g20.goals.create(team_id: 2, player_id: 16)
g20.goals.create(team_id: 2, player_id: 6)
g21 = Game.create(date: d1, team_left_id: team(:white), goals_left: 0, goals_right: 0, team_right_id: team(:green))
g22 = Game.create(date: d1, team_left_id: team(:white), goals_left: 2, goals_right: 1, team_right_id: team(:color1))
g22.goals.create(team_id: 4, player_id: 18)
g22.goals.create(team_id: 3, player_id: 7)
g22.goals.create(team_id: 3, player_id: 19)

d2 = '28.10.2019'.to_date
h1 = Game.create(date: d2, team_left_id: team(:white), goals_left: 2, goals_right: 1, team_right_id: team(:color1))
h1.goals.create(team_id: team(:white), player_id: 7)
h1.goals.create(team_id: team(:white), player_id: 22)
h1.goals.create(team_id: team(:color1), player_id: nil)
h2  = Game.create(date: d2, team_left_id: team(:white),  goals_left: 0, goals_right: 1, team_right_id: team(:green))
h2.goals.create(team_id: team(:green), player_id: 30)
h3  = Game.create(date: d2, team_left_id: team(:color1), goals_left: 1, goals_right: 1, team_right_id: team(:green))
h3.goals.create(team_id: team(:color1), player_id: 6)
h3.goals.create(team_id: team(:green), player_id: 8)
h4  = Game.create(date: d2, team_left_id: team(:color1), goals_left: 0, goals_right: 0, team_right_id: team(:color2))
h5  = Game.create(date: d2, team_left_id: team(:color1), goals_left: 1, goals_right: 1, team_right_id: team(:white))
h5.goals.create(team_id: team(:color1), player_id: 6)
h5.goals.create(team_id: team(:white), player_id: 1)
h6  = Game.create(date: d2, team_left_id: team(:color2), goals_left: 0, goals_right: 1, team_right_id: team(:green))
h6.goals.create(team_id: team(:green), player_id: 8)
h7  = Game.create(date: d2, team_left_id: team(:white),  goals_left: 0, goals_right: 0, team_right_id: team(:green))
h8  = Game.create(date: d2, team_left_id: team(:color2), goals_left: 0, goals_right: 2, team_right_id: team(:color1))
h8.goals.create(team_id: team(:color1), player_id: 6)
h8.goals.create(team_id: team(:color1), player_id: 6)
h9  = Game.create(date: d2, team_left_id: team(:white),  goals_left: 1, goals_right: 1, team_right_id: team(:color1))
h9.goals.create(team_id: team(:white), player_id: 7)
h9.goals.create(team_id: team(:color1), player_id: 31)
h10 = Game.create(date: d2, team_left_id: team(:color2), goals_left: 0, goals_right: 2, team_right_id: team(:green))
h10.goals.create(team_id: team(:green), player_id: 8)
h10.goals.create(team_id: team(:green), player_id: 8)
h11 = Game.create(date: d2, team_left_id: team(:white),  goals_left: 2, goals_right: 0, team_right_id: team(:green))
h11.goals.create(team_id: team(:white), player_id: 19)
h11.goals.create(team_id: team(:white), player_id: 21)
h12 = Game.create(date: d2, team_left_id: team(:white),  goals_left: 1, goals_right: 0, team_right_id: team(:color1))
h12.goals.create(team_id: team(:white), player_id: 19)
h13 = Game.create(date: d2, team_left_id: team(:white),  goals_left: 1, goals_right: 0, team_right_id: team(:color2))
h13.goals.create(team_id: team(:white), player_id: 1)
h14 = Game.create(date: d2, team_left_id: team(:white),  goals_left: 0, goals_right: 0, team_right_id: team(:green))
h15 = Game.create(date: d2, team_left_id: team(:color2), goals_left: 0, goals_right: 1, team_right_id: team(:color1))
h15.goals.create(team_id: team(:color1), player_id: 14)
h16 = Game.create(date: d2, team_left_id: team(:green),  goals_left: 0, goals_right: 1, team_right_id: team(:color1))
h16.goals.create(team_id: team(:color1), player_id: 18)
h17 = Game.create(date: d2, team_left_id: team(:white),  goals_left: 1, goals_right: 0, team_right_id: team(:color1))
h17.goals.create(team_id: team(:white), player_id: 21)
h18 = Game.create(date: d2, team_left_id: team(:white),  goals_left: 0, goals_right: 1, team_right_id: team(:color2))
h18.goals.create(team_id: team(:color2), player_id: 32)
h19 = Game.create(date: d2, team_left_id: team(:green),  goals_left: 1, goals_right: 1, team_right_id: team(:color2))
h19.goals.create(team_id: team(:green), player_id: 8)
h19.goals.create(team_id: team(:color2), player_id: 32)
h20 = Game.create(date: d2, team_left_id: team(:white),  goals_left: 0, goals_right: 1, team_right_id: team(:color1))
h20.goals.create(team_id: team(:color1), player_id: 23)
h21 = Game.create(date: d2, team_left_id: team(:green),  goals_left: 1, goals_right: 0, team_right_id: team(:color1))
h21.goals.create(team_id: team(:green), player_id: 30)
h22 = Game.create(date: d2, team_left_id: team(:green),  goals_left: 0, goals_right: 0, team_right_id: team(:color2))
