# frozen_string_literal: true

d2 = Day.create(sport_id: 1, season_id: 1, date: '28.10.2019'.to_date)
d2t1p1 = d2.day_players.create(season_id: 1, team_id: 1, player_id: 14)
d2t1p2 = d2.day_players.create(season_id: 1, team_id: 1, player_id: 18)
d2t1p3 = d2.day_players.create(season_id: 1, team_id: 1, player_id: 6)
d2t1p4 = d2.day_players.create(season_id: 1, team_id: 1, player_id: 23)
d2t1p5 = d2.day_players.create(season_id: 1, team_id: 1, player_id: 16)
d2t4p1 = d2.day_players.create(season_id: 1, team_id: 4, player_id: 35)
d2t4p2 = d2.day_players.create(season_id: 1, team_id: 4, player_id: 20)
d2t4p3 = d2.day_players.create(season_id: 1, team_id: 4, player_id: 32)
d2t3p1 = d2.day_players.create(season_id: 1, team_id: 3, player_id: 21)
d2t3p2 = d2.day_players.create(season_id: 1, team_id: 3, player_id: 17)
d2t3p3 = d2.day_players.create(season_id: 1, team_id: 3, player_id: 22)
d2t3p4 = d2.day_players.create(season_id: 1, team_id: 3, player_id: 19)
d2t3p5 = d2.day_players.create(season_id: 1, team_id: 3, player_id: 7)
d2t3p6 = d2.day_players.create(season_id: 1, team_id: 3, player_id: 1)
d2t2p1 = d2.day_players.create(season_id: 1, team_id: 2, player_id: 13)
d2t2p2 = d2.day_players.create(season_id: 1, team_id: 2, player_id: 10)
d2t2p3 = d2.day_players.create(season_id: 1, team_id: 2, player_id: 8)
d2t2p4 = d2.day_players.create(season_id: 1, team_id: 2, player_id: 30)
d2t2p5 = d2.day_players.create(season_id: 1, team_id: 2, player_id: 12)
d2t2p6 = d2.day_players.create(season_id: 1, team_id: 2, player_id: 3)
h1 = Game.create(day_id: d2.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 1)
h1.goals.create(season_id: 1, team_id: 3, player_id: 7)
h1.goals.create(season_id: 1, team_id: 3, player_id: 22)
h1.goals.create(season_id: 1, team_id: 1, player_id: nil)
h2  = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 1, team_right_id: 2)
h2.goals.create(season_id: 1, team_id: 2, player_id: 30)
h3  = Game.create(day_id: d2.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 2)
h3.goals.create(season_id: 1, team_id: 1, player_id: 6)
h3.goals.create(season_id: 1, team_id: 2, player_id: 8)
h4  = Game.create(day_id: d2.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 4)
h5  = Game.create(day_id: d2.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 3)
h5.goals.create(season_id: 1, team_id: 1, player_id: 6)
h5.goals.create(season_id: 1, team_id: 3, player_id: 1)
h6  = Game.create(day_id: d2.id, team_left_id: 4, goals_left: 0, goals_right: 1, team_right_id: 2)
h6.goals.create(season_id: 1, team_id: 2, player_id: 8)
h7  = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 0, team_right_id: 2)
h8  = Game.create(day_id: d2.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 1)
h8.goals.create(season_id: 1, team_id: 1, player_id: 6)
h8.goals.create(season_id: 1, team_id: 1, player_id: 6)
h9  = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 1, goals_right: 1, team_right_id: 1)
h9.goals.create(season_id: 1, team_id: 3, player_id: 7)
h9.goals.create(season_id: 1, team_id: 1, player_id: 31)
h10 = Game.create(day_id: d2.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 2)
h10.goals.create(season_id: 1, team_id: 2, player_id: 8)
h10.goals.create(season_id: 1, team_id: 2, player_id: 8)
h11 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 2, goals_right: 0, team_right_id: 2)
h11.goals.create(season_id: 1, team_id: 3, player_id: 19)
h11.goals.create(season_id: 1, team_id: 3, player_id: 21)
h12 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 1, goals_right: 0, team_right_id: 1)
h12.goals.create(season_id: 1, team_id: 3, player_id: 19)
h13 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 1, goals_right: 0, team_right_id: 4)
h13.goals.create(season_id: 1, team_id: 3, player_id: 1)
h14 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 0, team_right_id: 2)
h15 = Game.create(day_id: d2.id, team_left_id: 4, goals_left: 0, goals_right: 1, team_right_id: 1)
h15.goals.create(season_id: 1, team_id: 1, player_id: 14)
h16 = Game.create(day_id: d2.id, team_left_id: 2,  goals_left: 0, goals_right: 1, team_right_id: 1)
h16.goals.create(season_id: 1, team_id: 1, player_id: 18)
h17 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 1, goals_right: 0, team_right_id: 1)
h17.goals.create(season_id: 1, team_id: 3, player_id: 21)
h18 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 1, team_right_id: 4)
h18.goals.create(season_id: 1, team_id: 4, player_id: 32)
h19 = Game.create(day_id: d2.id, team_left_id: 2,  goals_left: 1, goals_right: 1, team_right_id: 4)
h19.goals.create(season_id: 1, team_id: 2, player_id: 8)
h19.goals.create(season_id: 1, team_id: 4, player_id: 32)
h20 = Game.create(day_id: d2.id, team_left_id: 3,  goals_left: 0, goals_right: 1, team_right_id: 1)
h20.goals.create(season_id: 1, team_id: 1, player_id: 23)
h21 = Game.create(day_id: d2.id, team_left_id: 2,  goals_left: 1, goals_right: 0, team_right_id: 1)
h21.goals.create(season_id: 1, team_id: 2, player_id: 30)
h22 = Game.create(day_id: d2.id, team_left_id: 2,  goals_left: 0, goals_right: 0, team_right_id: 4)
d2.day_rates!
