# frozen_string_literal: true

d4  = Day.create(sport_id: 1, season_id: 1, date: '11.11.2019'.to_date)
d4t1p1 = d4.day_players.create(season_id: 1, team_id: 1, player_id: 2)
d4t1p2 = d4.day_players.create(season_id: 1, team_id: 1, player_id: 6)
d4t1p3 = d4.day_players.create(season_id: 1, team_id: 1, player_id: 5)
d4t1p4 = d4.day_players.create(season_id: 1, team_id: 1, player_id: 25)
d4t1p5 = d4.day_players.create(season_id: 1, team_id: 1, player_id: 23)
d4t1p6 = d4.day_players.create(season_id: 1, team_id: 1, player_id: 14)
d4t1p7 = d4.day_players.create(season_id: 1, team_id: 1, player_id: 31)
d4t2p1 = d4.day_players.create(season_id: 1, team_id: 2, player_id: 4)
d4t2p2 = d4.day_players.create(season_id: 1, team_id: 2, player_id: 13)
d4t2p3 = d4.day_players.create(season_id: 1, team_id: 2, player_id: 10)
d4t2p4 = d4.day_players.create(season_id: 1, team_id: 2, player_id: 8)
d4t2p5 = d4.day_players.create(season_id: 1, team_id: 2, player_id: 12)
d4t2p6 = d4.day_players.create(season_id: 1, team_id: 2, player_id: 16)
d4t2p7 = d4.day_players.create(season_id: 1, team_id: 2, player_id: 30)
d4t3p1 = d4.day_players.create(season_id: 1, team_id: 3, player_id: 21)
d4t3p2 = d4.day_players.create(season_id: 1, team_id: 3, player_id: 19)
d4t3p3 = d4.day_players.create(season_id: 1, team_id: 3, player_id: 22)
d4t3p4 = d4.day_players.create(season_id: 1, team_id: 3, player_id: 1)
d4t3p5 = d4.day_players.create(season_id: 1, team_id: 3, player_id: 7)
d4t3p6 = d4.day_players.create(season_id: 1, team_id: 3, player_id: 28)
d4t3p7 = d4.day_players.create(season_id: 1, team_id: 3, player_id: 34)
j1  = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 1)
j1.goals.create(season_id: 1, team_id: 3, player_id: nil)
j2  = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
j2.goals.create(season_id: 1, team_id: 2, player_id: 13)
j3  = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 2)
j3.goals.create(season_id: 1, team_id: 2, player_id: 13)
j3.goals.create(season_id: 1, team_id: 1, player_id: 23)
j3.goals.create(season_id: 1, team_id: 1, player_id: 25)
j4  = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 3)
j4.goals.create(season_id: 1, team_id: 3, player_id: 1)
j4.goals.create(season_id: 1, team_id: 3, player_id: 19)
j5  = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 3)
j5.goals.create(season_id: 1, team_id: 2, player_id: 4)
j6  = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
j6.goals.create(season_id: 1, team_id: 1, player_id: 25)
j6.goals.create(season_id: 1, team_id: 1, player_id: 31)
j7  = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 1)
j7.goals.create(season_id: 1, team_id: 1, player_id: nil)
j8  = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 2, goals_right: 0, team_right_id: 1)
j8.goals.create(season_id: 1, team_id: 2, player_id: 8)
j8.goals.create(season_id: 1, team_id: 2, player_id: 10)
j9  = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 3)
j9.goals.create(season_id: 1, team_id: 1, player_id: 25)
j9.goals.create(season_id: 1, team_id: 3, player_id: 21)
j9.goals.create(season_id: 1, team_id: 3, player_id: 19)
j10 = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 3)
j10.goals.create(season_id: 1, team_id: 2, player_id: 4)
j10.goals.create(season_id: 1, team_id: 3, player_id: 7)
j11 = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 2, goals_right: 0, team_right_id: 1)
j11.goals.create(season_id: 1, team_id: 2, player_id: 13)
j11.goals.create(season_id: 1, team_id: 2, player_id: 8)
j12 = Game.create(day_id: d4.id, team_left_id: 2, goals_left: 1, goals_right: 2, team_right_id: 3)
j12.goals.create(season_id: 1, team_id: 2, player_id: 8)
j12.goals.create(season_id: 1, team_id: 3, player_id: 7)
j12.goals.create(season_id: 1, team_id: 3, player_id: 34)
j13 = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 3)
j13.goals.create(season_id: 1, team_id: 1, player_id: 25)
j13.goals.create(season_id: 1, team_id: 3, player_id: 7)
j14 = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 2)
j14.goals.create(season_id: 1, team_id: 2, player_id: 8)
j14.goals.create(season_id: 1, team_id: 2, player_id: 4)
j15 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 1, goals_right: 2, team_right_id: 2)
j15.goals.create(season_id: 1, team_id: 3, player_id: 1)
j15.goals.create(season_id: 1, team_id: 2, player_id: 8)
j15.goals.create(season_id: 1, team_id: 2, player_id: 4)
j16 = Game.create(day_id: d4.id, team_left_id: 1, goals_left: 0, goals_right: 1, team_right_id: 2)
j16.goals.create(season_id: 1, team_id: 2, player_id: 8)
j17 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 2)
j17.goals.create(season_id: 1, team_id: 2, player_id: 13)
j17.goals.create(season_id: 1, team_id: 3, player_id: 21)
j18 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
j18.goals.create(season_id: 1, team_id: 3, player_id: 1)
j18.goals.create(season_id: 1, team_id: 3, player_id: 1)
j19 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 2)
j19.goals.create(season_id: 1, team_id: 3, player_id: 1)
j19.goals.create(season_id: 1, team_id: 3, player_id: 7)
j19.goals.create(season_id: 1, team_id: 2, player_id: 8)
j20 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
j20.goals.create(season_id: 1, team_id: 3, player_id: 1)
j20.goals.create(season_id: 1, team_id: 3, player_id: 34)
j21 = Game.create(day_id: d4.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 2)
j21.goals.create(season_id: 1, team_id: 3, player_id: 1)
j21.goals.create(season_id: 1, team_id: 2, player_id: 4)
d4.day_rates!
