# frozen_string_literal: true

d3 = Day.create(sport_id: 1, season_id: 1, date: '06.11.2019'.to_date)
d3t1p1 = d3.day_players.create(season_id: 1, team_id: 1, player_id: 1)
d3t1p2 = d3.day_players.create(season_id: 1, team_id: 1, player_id: 33)
d3t1p3 = d3.day_players.create(season_id: 1, team_id: 1, player_id: 16)
d3t1p4 = d3.day_players.create(season_id: 1, team_id: 1, player_id: 6)
d3t1p5 = d3.day_players.create(season_id: 1, team_id: 1, player_id: 23)
d3t1p6 = d3.day_players.create(season_id: 1, team_id: 1, player_id: 32)
d3t2p1 = d3.day_players.create(season_id: 1, team_id: 2, player_id: 4)
d3t2p2 = d3.day_players.create(season_id: 1, team_id: 2, player_id: 10)
d3t2p3 = d3.day_players.create(season_id: 1, team_id: 2, player_id: 12)
d3t2p4 = d3.day_players.create(season_id: 1, team_id: 2, player_id: 13)
d3t2p5 = d3.day_players.create(season_id: 1, team_id: 2, player_id: 3)
d3t3p1 = d3.day_players.create(season_id: 1, team_id: 3, player_id: 21)
d3t3p2 = d3.day_players.create(season_id: 1, team_id: 3, player_id: 17)
d3t3p3 = d3.day_players.create(season_id: 1, team_id: 3, player_id: 7)
d3t3p4 = d3.day_players.create(season_id: 1, team_id: 3, player_id: 19)
d3t3p5 = d3.day_players.create(season_id: 1, team_id: 3, player_id: 34)
i1  = Game.create(day_id: d3.id, team_left_id: 2, goals_left: 0, goals_right: 0, team_right_id: 1)
i2  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 2)
i2.goals.create(season_id: 1, team_id: 3, player_id: 21)
i2.goals.create(season_id: 1, team_id: 3, player_id: 17)
i3  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 1)
i3.goals.create(season_id: 1, team_id: 3, player_id: 19)
i3.goals.create(season_id: 1, team_id: 3, player_id: 7)
i3.goals.create(season_id: 1, team_id: 1, player_id: 33)
i4  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 2)
i5  = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 2)
i5.goals.create(season_id: 1, team_id: 1, player_id: 16)
i5.goals.create(season_id: 1, team_id: 2, player_id: 4)
i5.goals.create(season_id: 1, team_id: 2, player_id: 12)
i6  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 2)
i6.goals.create(season_id: 1, team_id: 3, player_id: 21)
i6.goals.create(season_id: 1, team_id: 3, player_id: 17)
i6.goals.create(season_id: 1, team_id: 2, player_id: 4)
i7  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 1)
i8  = Game.create(day_id: d3.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
i8.goals.create(season_id: 1, team_id: 1, player_id: 1)
i8.goals.create(season_id: 1, team_id: 1, player_id: 14)
i9  = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 1)
i9.goals.create(season_id: 1, team_id: 3, player_id: 19)
i10 = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 2)
i11 = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 2)
i11.goals.create(season_id: 1, team_id: 2, player_id: 4)
i11.goals.create(season_id: 1, team_id: 2, player_id: 13)
i12 = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 1, goals_right: 2, team_right_id: 2)
i12.goals.create(season_id: 1, team_id: 3, player_id: 19)
i12.goals.create(season_id: 1, team_id: 2, player_id: 4)
i12.goals.create(season_id: 1, team_id: 2, player_id: 3)
i13 = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
i13.goals.create(season_id: 1, team_id: 1, player_id: 1)
i13.goals.create(season_id: 1, team_id: 1, player_id: 1)
i14 = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 3)
i14.goals.create(season_id: 1, team_id: 1, player_id: 23)
i14.goals.create(season_id: 1, team_id: 3, player_id: 19)
i15 = Game.create(day_id: d3.id, team_left_id: 2, goals_left: 1, goals_right: 0, team_right_id: 3)
i15.goals.create(season_id: 1, team_id: 2, player_id: 3)
i16 = Game.create(day_id: d3.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 1)
i16.goals.create(season_id: 1, team_id: 2, player_id: 13)
i16.goals.create(season_id: 1, team_id: 1, player_id: 32)
i17 = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
i17.goals.create(season_id: 1, team_id: 3, player_id: 7)
i17.goals.create(season_id: 1, team_id: 3, player_id: 34)
i18 = Game.create(day_id: d3.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
i18.goals.create(season_id: 1, team_id: 2, player_id: 4)
i19 = Game.create(day_id: d3.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 2)
i19.goals.create(season_id: 1, team_id: 1, player_id: 6)
i19.goals.create(season_id: 1, team_id: 2, player_id: 12)
i19.goals.create(season_id: 1, team_id: 2, player_id: 13)
d3.day_rates!
